### ISSUE TITLE
Loottables doesn't work

### ISSUE THREAD

**Issue by balbino-cpu** [DRE2N/ItemsXL#21]
I don't know if it's my problem but for the past 2 hours I've been struggling to make my custom loottable work in a custom mob.

Mob yml:
```
hasAI: true
hasGravity: true
maxAir: 300
equipment:

  ==: de.erethon.caliburn.loottable.LootTable
canPickupItems: false
isInvulnerable: false
isCollidable: true
removeWhenFarAway: true
species: skeleton
isPersistent: true
equipment:
  ==: de.erethon.caliburn.loottable.LootTable
  'leggings':
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: DIAMOND_LEGGINGS
    chance: 0.5
  'mainHand':
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: ENCHANTED_BOOK
      meta:
        ==: ItemMeta
        meta-type: ENCHANTED
        stored-enchants:
          OXYGEN: 3
      chance: 10.0
drops:
  '0':
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2586
      type: IRON_BLOCK
    chance: 5.0
  '1':
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2586
      type: OAK_LEAVES
    chance: 10.0
  '2':
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2586
      type: OAK_SIGN
      amount: 16
    chance: 100.0
name: '1882'
isCustomNameVisible: false
isGlowing: false
isSilent: false
```
Also the chances for the equipment doesn't work.

I alredy tried reloading the server, reloading the plugin...

**Comment by Sataniel98** [comment]
Everything below `  ==: de.erethon.caliburn.loottable.LootTable` is not in the equipment section. See https://github.com/DRE2N/DungeonsXL/wiki/data-structure-guide#map

**Comment by balbino-cpu** [comment]
I removed the `==: de.erethon.caliburn.loottable.LootTable` and putted it in the drops and it doesn't work. The equipment has dissapeared and the loottable doesn't work. Also tried to remove `==: de.erethon.caliburn.loottable.LootTable` from everything. Doesn't work

**Comment by Sataniel98** [comment]
Don't remove it, just add the same indents to the values after it that still belong to equipment.

**Comment by balbino-cpu** [comment]
Did it, the custommob.yml looks like this and it doesnt work
```
hasAI: true
hasGravity: true
maxAir: 300
canPickupItems: false
isInvulnerable: false
isCollidable: true
removeWhenFarAway: true
species: skeleton
isPersistent: true

drops:
  ==: de.erethon.caliburn.loottable.LootTable
  '0':
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2586
      type: IRON_BLOCK
    chance: 100.0


name: 'coso'
isCustomNameVisible: false
isGlowing: false
isSilent: false
```
